# Generated by Django 5.2.4 on 2025-07-23 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employments',
            new_name='Employment',
        ),
    ]
